### ISSUE TITLE
Address block base address >0x80000000 produce errors

### ISSUE THREAD

**Issue by 0tti** [kactus2/kactus2dev#41]
As soon as block addresses above 0x80000000 are used, errors occures.

- the integrity check shows errors
- the addresses in the "Memory maps visualization" are extending to 64 bit with leading F 
- the tree truns red

Example Address Block table:
Name/Base/Range/Width
MODUL_A 'h40000000 4 32
MODUL_B 'h80000000 4 32

The XML file is not influenced. the addresses are written correctly.
Tested with 3.6 and 3.8

**Comment by epekkar** [comment]
Hi 0tti,
I'll look into the issue. I am guessing it is related to how the addresses are interpret at error checking and should be easy to fix.

**Comment by epekkar** [comment]
This is fixed in the latest version 3.9.0. 
![image](https://user-images.githubusercontent.com/19324755/133039020-37fcfb54-1e19-43b6-8802-f399233d226d.png)

**Comment by 0tti** [comment]
With 3.9.168 the visualization is now correct. 
But the other errors remain.
- the integrity check shows errors (save and output window)
- the tree (MemoryMaps...) turns red
